proxy:
  secretToken: "65b2bbc5fee921f00026ca3355ed3423f88b7bc2738f6b9823ad79d1282b3c8f"
  https:
    enabled: false

auth:
  type: dummy
  dummy:
    password: 'belino'
  whitelist:
    users:
      - admin
